### ISSUE TITLE
npm audit vulnerabilities

### ISSUE THREAD

**Issue by akuma1** [MonsantoCo/express-client-validator#1]
npm audit reports 4 vulnerabilities in this project (2 low, 1 high, 1 critical).
Critical vulnerability is with mocha version used for unit testing so it may not have much impact.
High vulnerability is with outdated version of pg-promise, does this library really need pg-promise? 

It will be nice to have these npm audit issues addressed in the next version of this library.

**Comment by pjcras** [comment]
Thanks @akuma1 for the PR, this has been merged. I have published a new version (1.1.0) of the library
